seed: 42
device: auto

paths:
  log_dir: logs
  plot_dir: plots
  model_dir: models

data:
  nusc_root: /ocean/projects/tra250008p/slin24/datasets/nuscenes
  trajdata_cache_dir: /ocean/projects/tra250008p/slin24/MetaLearning/adaptive-prediction/traj_cache_nusc_full
  train_tags:
    - nusc_trainval-train
    - nusc_trainval-boston-train  
    - nusc_trainval-singapore-train
  eval_tags:
    - nusc_trainval-train_val
    - nusc_trainval-boston-train_val
    - nusc_trainval-singapore-train_val

training:
  dt: 0.5
  history_sec: 2.0
  prediction_sec: 6.0
  preprocess_workers: 4
  epochs: 50
  quick_epochs: 10
  steps_per_epoch: 2000
  quick_steps_per_epoch: 500
  batch_size: 1
  cvar_alpha: 0.8
  learning_rate: 0.01
  bayes_lr: 0.05
  sampler:
    angle_deg_thresh: 12.0
    speed_limit_ms: 16.7
    est_samples: 3000
    proportions: 
  cost_normalization:
    jerk_scale: 10.0
    acc_scale: 5.0  
    smooth_scale: 2.0
    lane_scale: 1.0

model:
  cost_dim: 4

rules:
  X_stop: 50.0

outer_model:
  enable: true
  path: /ocean/projects/tra250008p/slin24/MetaLearning/adaptive-prediction/experiments/nuScenes/models
  ckpt: nusc_mm_base_tpp-11_Sep_2022_19_15_45
  iteration: 20
  max_modes: 6
  tpp:
    eager: false
    force_cpu_load: true
    fallback_std: 2.0
